/**
 * PKCE (Proof Key for Code Exchange) Utilities
 *
 * Implements RFC 7636 PKCE for OAuth 2.0 Authorization Code Flow.
 * Uses Web Crypto APIs available in Node.js and Edge runtimes.
 *
 * @see https://datatracker.ietf.org/doc/html/rfc7636
 * @module lib/auth/pkce
 */

/**
 * Generate a cryptographically secure code verifier.
 *
 * The verifier is a high-entropy random string used in the PKCE flow.
 * It should be stored temporarily (e.g., in a secure httpOnly cookie)
 * and sent during token exchange.
 *
 * @returns A 64-character URL-safe base64 encoded random string
 *
 * @example
 * ```typescript
 * const verifier = generateVerifier();
 * // Store in httpOnly cookie for callback
 * ```
 */
export function generateVerifier(): string {
  // 32 bytes = 256 bits of entropy, URL-safe base64 encoded
  const randomBytes = new Uint8Array(32);
  crypto.getRandomValues(randomBytes);

  return base64UrlEncode(randomBytes);
}

/**
 * Generate a code challenge from a verifier using S256 method.
 *
 * Creates a SHA-256 hash of the verifier, then base64url encodes it.
 * The challenge is sent in the authorization request, while the
 * verifier is sent during token exchange.
 *
 * @param verifier - The code verifier generated by generateVerifier()
 * @returns Promise resolving to base64url-encoded SHA-256 hash
 *
 * @example
 * ```typescript
 * const verifier = generateVerifier();
 * const challenge = await generateChallenge(verifier);
 * // Send challenge to authorization endpoint
 * ```
 */
export async function generateChallenge(verifier: string): Promise<string> {
  const encoder = new TextEncoder();
  const data = encoder.encode(verifier);

  const hashBuffer = await crypto.subtle.digest("SHA-256", data);
  const hashArray = new Uint8Array(hashBuffer);

  return base64UrlEncode(hashArray);
}

/**
 * Encode bytes to URL-safe base64 (RFC 4648 Section 5).
 *
 * Standard base64 is modified:
 * - '+' → '-'
 * - '/' → '_'
 * - Padding '=' is removed
 *
 * @param bytes - Uint8Array to encode
 * @returns URL-safe base64 string without padding
 */
function base64UrlEncode(bytes: Uint8Array): string {
  // Convert bytes to base64
  let base64 = "";
  for (const byte of bytes) {
    base64 += String.fromCharCode(byte);
  }
  const encoded = btoa(base64);

  // Make URL-safe: replace + with -, / with _, remove padding
  return encoded.replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}
