module.exports = {
  preset: "ts-jest",
  testEnvironment: "jsdom",
  roots: ["<rootDir>/src"],
  testMatch: ["**/__tests__/**/*.ts?(x)", "**/?(*.)+(spec|test).ts?(x)"],
  transform: {
    "^.+\\.tsx?$": [
      "ts-jest",
      {
        isolatedModules: true,
        tsconfig: {
          jsx: "react-jsx",
        },
      },
    ],
  },
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/src/$1",
    "\\.(css|less|scss|sass)$": "identity-obj-proxy",
  },
  setupFilesAfterEnv: ["<rootDir>/jest.setup.js"],
  collectCoverageFrom: [
    "src/**/*.{ts,tsx}",
    "!src/**/*.d.ts",
    "!src/**/*.stories.tsx",
    "!src/**/index.ts",
    "!src/**/*.example.tsx",
    "!src/**/*.example.ts",
    "!src/extended.ts",
    "!src/components/ui/accordion.tsx",
    "!src/components/ui/alert.tsx",
    "!src/components/ui/alert-dialog.tsx",
    "!src/components/ui/aspect-ratio.tsx",
    "!src/components/ui/avatar.tsx",
    "!src/components/ui/breadcrumb.tsx",
    "!src/components/ui/button-group.tsx",
    "!src/components/ui/calendar.tsx",
    "!src/components/ui/card.tsx",
    "!src/components/ui/carousel.tsx",
    "!src/components/ui/chart.tsx",
    "!src/components/ui/checkbox.tsx",
    "!src/components/ui/collapsible.tsx",
    "!src/components/ui/combobox.tsx",
    "!src/components/ui/command.tsx",
    "!src/components/ui/context-menu.tsx",
    "!src/components/ui/drawer.tsx",
    "!src/components/ui/field.tsx",
    "!src/components/ui/form.tsx",
    "!src/components/ui/hover-card.tsx",
    "!src/components/ui/input-group.tsx",
    "!src/components/ui/input-otp.tsx",
    "!src/components/ui/item.tsx",
    "!src/components/ui/kbd.tsx",
    "!src/components/ui/label.tsx",
    "!src/components/ui/loader.tsx",
    "!src/components/ui/menubar.tsx",
    "!src/components/ui/native-select.tsx",
    "!src/components/ui/navigation-menu.tsx",
    "!src/components/ui/pagination.tsx",
    "!src/components/ui/popover.tsx",
    "!src/components/ui/progress.tsx",
    "!src/components/ui/radio-group.tsx",
    "!src/components/ui/resizable.tsx",
    "!src/components/ui/scroll-area.tsx",
    "!src/components/ui/separator.tsx",
    "!src/components/ui/sheet.tsx",
    "!src/components/ui/slider.tsx",
    "!src/components/ui/sonner.tsx",
    "!src/components/ui/spinner.tsx",
    "!src/components/ui/table.tsx",
    "!src/components/ui/tabs.tsx",
    "!src/components/ui/textarea.tsx",
    "!src/components/ui/theme-toggle.tsx",
    "!src/components/ui/toggle.tsx",
    "!src/components/ui/toggle-group.tsx",
  ],
  coverageThreshold: {
    global: {
      branches: 60,
      functions: 65,
      lines: 70,
      statements: 70,
    },
    // Only enforce coverage on custom utilities and business logic
    "./src/lib/*.{ts,tsx}": {
      branches: 70,
      functions: 75,
      lines: 75,
      statements: 75,
    },
  },
};
